config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  devise_for :users
  root to: 'home#index'

  resources :questions do
   get 'new_question',:on=> :collection
   get 'question_new_search',:on=> :collection
   get 'delete_question',:on=> :collection
   get 'update_question',:on=> :collection
   post 'create_question',:on=> :collection
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers
  has_many :options, dependent: :destroy
  accepts_nested_attributes_for :options, reject_if: proc { |attributes| attributes['name'].blank? }

  scope :single_multiple_questions, {:conditions => ['type in ( ? )', ['SingleAnswerQuestion', 'MultipleAnswerQuestion']]}

  after_update :save_options
 # validate :question_validate

  def question_validate
    errors[:base] << ("1_Question should not be blank") if name.blank?
    errors[:base] << ("1_Question type should not be blank") if type.blank?
  end

  def boolean=(boolean)
    options.destroy(options)
    options.reload
    options.build(boolean)
  end

  # Since it is STI we cannot directly assign type so use this method
  # example: we cannot assign like question.type=
  # use question.question_type=

  def question_type=(sType)
    self[:type]=sType
  end

  # We can't directly access the type attribute in question.
  # we can access that by @question[:type]

  def question_type
    self[:type]
  end

  def new_options=(new_options)
    debugger
    new_options.collect do |option|
      if option[:name]
        options.build(option) unless (option[:name].empty? or option[:name].delete(' ').eql?(''))
      end
    end
  end

  # This setter is only for multiple or single question options
  # Options will be in the string form seperated by "\n"
  def text_options=(text_options)
    text_options.strip.split("\r\n").collect(&:strip).uniq.collect { |name| options.build(:name => name) }
  end

  def existing_options=(existing_options)
    options.reject(&:new_record?).each do |option|
      attributes = existing_options[option.id.to_s]
      if attributes and !attributes[:name].empty? and !attributes[:name].delete(' ').eql?('')
        option.attributes = attributes
      else
        options.find(option.id).delete
      end
    end
  end

  # This method is called in the after_update
  def save_options
    debugger
    options.collect { |option| option.save }
  end


  # To get the answer from the params[:questionnaire_submission][:new_answer] hash
  def get_answer(new_questions) # new_questions = params[:questionnaire_submission][:new_answer]
    question_type = QUESTION_ANSWER_CONVERTER[self.class.to_s]
    if ['SingleAnswer', 'MultipleAnswer'].include?(question_type)
      answers = new_questions[question_type]
      answer = answers ? answers[self.id.to_s] : nil
      other_answers = new_questions[SINGLE_MULTIPLE_OTHER_MAP[self.class.to_s]]
      other_answer = other_answers ? other_answers[self.id.to_s] : nil
      if question_type == 'MultipleAnswer'
        [answer, other_answer]
      else
        (answer || other_answer || "").to_s
      end
    else
      (new_questions[question_type].values if new_questions[question_type]).to_s
    end
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @questions = Question.paginate(:page => params[:page], :per_page => 5)
  end

  def edit
    @question = Question.find(params[:id])
  end

  def new_question
    @question = Question.new
  end

  def create_question
    @question = Question.new(params_questions)
    debugger
    @question.save
    render :partial => 'questions/question_list_temp'
  end

  def update_question
    params[:question][:existing_options] ||= {}
    params[:question][:verification_method_id] = params[:question][:verification_method_id], params[:verification_method_message]
    @question = Question.find(params[:id])
    render :template => 'questions/edit_question'
  end

  def delete_question
    @questions = Question.find(params[:document][:ids])
    @questions.each do |question|
      question.options.destroy_all
      question.verification_method.delete if question.verification_method
      question.delete
    end
  end

  def add_options_in_text
    render :partial => 'add_options_in_text'
  end

  def add_view_type
    @question = params[:question_id].blank? ? Question.new : Question.find( params[:question_id] )
    render :partial => 'view_type'
  end

  def pagination(template, component_hash, element_id)
    respond_to do |format|
      format.html do
        render :action => template
      end
      format.js do
        render :update do |page|
          page.replace_html element_id, component_table_list(component_hash), :page => params[:page]
        end
      end
    end
  end


  def params_questions
    debugger
    #params.required(:questions).permit(:question_type, :name, :prefilled_field_hint, :options_attributes=> :name)
    params.required(:questions).permit(:question_type, :name, :prefilled_field_hint, :options_attributes=> [:name, :default_value])
  end

end

app/views/questions/_add_options_in_text.html.erb
<% options = params[:id].blank? ? nil : Question.find(params[:id]).options.collect(&:name).join("\n") %>
<%= content_tag(:span, text_area( :question, :option, :value => options, :name => 'question[text_options]', :cols => "30", :rows=> "5" ) ) %>

app/views/questions/_form.html.erb
<div class="article_new_main">
  <%= form_for :questions, :url => {:action => (@question.new_record?) ? "create_question" : "update_question", :id => @question} do |f| -%>

      <div class="validation_box">
        <%= raw error_messages_sorted(@question) %>
      </div>

      <% if params[:action]=="edit" %>
          <div class="group_fixed">
            <label for="text_head">Question id :</label>
            <p><%= @question.id %></p>
          </div>
      <% end %>

      <div class="group_fixed">
        <label for="text_head">Select a Type of Question <span>* </span>:</label>
        <%= f.select 'question_type', QUESTION_TYPES, {:include_blank => "Select"}, :class => 'question_change_type select_box' %>
        <%= content_tag(:span, nil, :id => 'view_type') %>
      </div>

      <div class="group_fixed">
        <label for="text_head">Question Text <span>* </span>:</label>
        <%= f.text_field :name, :class => 'input_text', :size => 30 %>
      </div>

      <div id='field_length_label' class="asset_form">
        <div class="group_fixed">
          <label for="text_head">Input field length :</label>
          <%= f.text_field :input_field_length, :class => 'input_text_question input_text', :size => 30 %>
        </div>
      </div>

      <div id='prefilled_hint'>
        <div class="group_fixed">
          <label for="text_head">Pre-filled field hint :</label>
          <%= f.text_field :prefilled_field_hint, :class => 'input_text', :size => 30 %>
        </div>
      </div>

     <div id='max_char' style='display:none'>
        <div class="group_fixed">
          <label for="text_head">Maximum Length :</label>
          <%= f.text_field :max_length, :onkeypress => 'return blockNonNumbers(this, event, true, true);', :class => 'input_text', :size => 30 %>
        </div>
      </div>
      <div id='max_val' style='display:none'>
        <div class="group_fixed">
          <label for="text_head">Maximum Value :</label>
          <%= f.text_field :max_number, :class => 'input_text', :size => 30 %>
        </div>
      </div>

      <div id='min_val' style='display:none'>
        <div class="group_fixed">
          <label for="text_head">Minimum Value :</label>
          <%= f.text_field :min_number, :class => 'input_text', :size => 30 %>
        </div>
      </div>

      <div id='positive_val' style='display:none'>
        <div class="group_fixed">
          <label for="text_head">Positive Value :</label>
          <% value = @question.new_record? ? '' : (@question.options.first.positive_value unless @question.options.blank?) %>
          <%= text_field :boolean, :positive_value, :value => value, :class => 'input_text', :name => 'question[boolean][positive_value]', :size => 30 %>
        </div>
      </div>

      <div id='negative_val' style='display:none'>
        <div class="group_fixed">
          <label for="text_head">Negative Value :</label>
          <% value = @question.new_record? ? '' : (@question.options.first.negative_value unless @question.options.blank?) %>
          <%= text_field :boolean, :negative_value, :value => value, :class => 'input_text', :name => 'question[boolean][negative_value]', :size => 30 %>
        </div>
      </div>
      <div class="question_form_option" id="option_list">
        <ul style="list-style-type:none;" id='add_option_txt_field'>
          <%= render :partial => '/questions/option', :collection => @question.options %>
          <%#= content_tag(:li, link_to('Import', :action => 'add_option_from_text', :id => @question.id ) ) unless @question.new_record? %>
        </ul>
      </div>

      <div id='add_option' class="remove_part_ajax">
       <span class="button">
         <a href="javascript:void(0)"
            data-url="/admin/questions/add_options_in_text"
            data-update="option_list"
            data-paramtype="params_get"
            data-param=""
            data-remove="remove_part_ajax"
            class="question_import_option ajax_form_call">Import Options
         </a>
       </span>
        <span class="button"><a href="javascript:void(0)" class="add_new_option">Add New Option</a></span>
      </div>

        <div class="group_fixed">
          <%= submit_tag (@question and @question.new_record?) ? 'Save' : 'Update' %>
        </div>

  <% end %>
</div>

app/views/questions/_option.html.erb
<% new_or_existing = option.new_record? ? 'new' : 'existing' %>
<% prefix = "question[#{new_or_existing}_options][]" %>

<%= fields_for prefix, option do |qf| -%>
	<li class="option" style="line-height:20px;"><nobr> Option: <%= qf.text_field 'name',:class=>'input_text',:size=>30 %>Default<%= qf.check_box 'default_value',:class=>''%> &nbsp;&nbsp;
    	<a onclick="javascript:jQuery(this).parent().parent('li').remove();" href="javascript:void(0);">
			<%= image_tag "/images/cancel.png", :alt=>"Remove", :height => "15" %>
        </a>
        <%#= link_to_function "remove" , :onclick => "$(this).up('.option').remove()" %>
        </nobr>
	</li>
<% end %>
<%#= sortable_element("add_option_txt_field", :onUpdate=>"function(){return false}") %>

app/views/questions/_question.html.erb
<% action_selection = {:edit => 'edit', :delete_question => 'delete_question', :editnaire => 'editnaire'} %>
<% url_params = Proc.new{|action|

		if params[:campaign_id]
			{:controller => 'questions', :action => action, :id => question.id, :campaign_id => params[:campaign_id] }
		elsif params[:company_id]
			{:controller => 'questions', :action => action, :id => question.id, :company_id => params[:company_id] }
		else
			{:controller => 'questions', :action => action, :id => question.id }
		end

	}
%>

<tr>
	<%=content_tag(:td, (question.id || "-"), :class => "list_table")%>
	<%=content_tag(:td, ((question.name) ? link_to("#{question.name}", url_params.call(action_selection[:edit])) : "-"), :class => "list_table")%>
	<%=content_tag(:td, (question.type || "-"), :class => "list_table")%>

	<% content_tag(:td, :class => "list_table") do %>
	    <%= unless question.questionnaires.blank?
			    question.questionnaires.collect do |questionnaire|
					if questionnaire.name
						auhtorized?('admin/questionnaires', 'editnaire') ? link_to("#{questionnaire.name}", url_params.call(action_selection[:editnaire]).merge({:id => questionnaire.id, :controller => 'questionnaires'})) : questionnaire.name
					else
						'-'
					end
				end.join(', ')
		    else
			    link_to(image_tag("/images/dust_bin.jpeg", :border => 0, :width => 15, :height => 15, :alt => "Delete"), url_params.call(action_selection[:delete_question]), {:confirm => "Really delete #{question.name}?"})
	    	end %>
    <% end %>
</tr>

app/views/questions/_question_button.html.erb
<div class="right_section_head">
<ul>
    <li class="button">
    
        <%=link_to 'New Question',{:controller=>'admin/questions',:action => 'new_question',:campaign_id=>params[:campaign_id]} %>
    
 </li>
</ul>
</div>

app/views/questions/_question_list_temp.html.erb
<h1>Succesfully created</h1>

app/views/questions/_view_type.html.erb
<%= select(:question, :view_type, params[:view_options].constantize ) %>

app/views/questions/edit.html.erb
<%= render partial: 'form' %>

app/views/questions/index.html.erb
<div class="section_block full_section">
  <h2>Question Search</h2>

  <div class="section_content">
    <%= form_tag({:controller => "questions", :action => "question_new_search"}, {:method => "get"}) %>
    <div class="group_fixed">
      <label>Question ID :</label>
      <%= text_field :question, :id, :class => "input_text" %>
    </div>
    <div class="group_fixed">
      <label>Question Name :</label>
      <%= text_field :question, :name, :class => "input_text" %>
    </div>
    <div class="group_fixed">
      <%= content_tag(:td, submit_tag("Search"), :class => "button") %>
    </div>
    </form>
  </div>
</div>

<table border="2">
  <tr>
    <th>Id :</th>
    <th>Name :</th>
    <th>Type</th>
  </tr>
  <% @questions.each do |question| %>
      <tr>
        <td><%= (question.id) ? (question.id) : '-' %></td>
        <td><%= (question.name) ? link_to( "#{question.name}", edit_question_path(question) ) : '-' %></td>
        <td><%= (question.type) ? (question.type) : '-' %></td>
      </tr>
  <% end %>

</table><br />
<%= will_paginate @questions %>

app/views/questions/new_question.html.erb
<%= link_to('All Question', questions_path) %>
<%= render :partial => 'questions/form' %>